### ISSUE TITLE
Vote submission doesn't work with Trust Wallet

### ISSUE THREAD

**Issue by JSeiferth** [grants-stack-frontier/op-rf-6#105]
### What was the URL where the error occurred?

- 

### What happened?

User reports they get an error when submitting their ballot. They 
1. Click submit ballot
2. Sign the message in their wallet
3. Get an infinite loading screen

User is using Safari + Trust wallet
![telegram-cloud-photo-size-1-4994530173764349184-y](https://github.com/user-attachments/assets/5b11e040-b2b5-4339-8e87-5b9bc08a06ba)

Console log
![telegram-cloud-photo-size-1-4996781973578035040-y](https://github.com/user-attachments/assets/cadc66c6-1d2e-419c-9f6b-06e6a3d0eb3a)

### What should have happened instead?

User Should be able to submit ballot

### Steps to Reproduce

1. Use Safari + Trust wallet
2. Click submit ballot
3. Sign the message in their wallet
4. Get an infinite loading screen

**Comment by geovgy** [comment]
@JSeiferth I am unable to reproduce this issue with my own trust wallet and safari browser. From the image, looks like they just need to SIWE again as the session token is missing, which is causing the 401 error. Since trust wallet doesn't have a browser extension for safari, it could have been one of those weird WalletConnect issues when connecting to its mobile wallet. I've had that experience in the past before with other mobile wallets when an app has prompted to sign a message and yet the message doesn't show in my wallet to sign immediately (and a few times not at all or doesn't relay signature back quickly). Has happened to me during times of bad internet connection or returning from a previous WC session on a site.

Steps I'd encourage the user to do:
1. Disconnect wallet. Then reconnect and sign message. (A new WC session might be needed)
2. If step 1 doesn't work, try on a different browser. (Shouldn't matter which browser they're on but might as well.)

If the issue still persists afterwards, please let me know.
