### ISSUE TITLE
Logo is missing

### ISSUE THREAD

**Issue by meglister** [grants-stack-frontier/op-rf-6#87]
Not sure if this is a bug on our end or elsewhere in the stack. The OSO logo is broken here: https://develop-op-rf-6.up.railway.app/project/0x1bd2ea66a88fa468d299997ef5a79bdf157b7d4b0f91d99410daaacb3f998358

**Comment by meglister** [comment]
Also happening here: https://develop-op-rf-6.up.railway.app/project/0xc68d5a1b9170d4f560a4e7b18901e8cdcefca36667dd4d9559ea473020807594

**Comment by geovgy** [comment]
I'm unsure why this bug is occurring. It's inconsistent and unusual. The API returns a valid image url and our frontend allows that domain and all of its pathnames for rendering the image. Yet, it doesn't render on all deployments, only some. For example, I see the image render fine in the second link you shared but doesn't appear on the same page in [production](https://round6.optimism.io/project/0xc68d5a1b9170d4f560a4e7b18901e8cdcefca36667dd4d9559ea473020807594).

**Comment by vidvidvid** [comment]
i think i fixed this! :)
[main](https://round6.optimism.io/project/0xc68d5a1b9170d4f560a4e7b18901e8cdcefca36667dd4d9559ea473020807594)
[develop](https://develop-op-rf-6.up.railway.app/project/0xc68d5a1b9170d4f560a4e7b18901e8cdcefca36667dd4d9559ea473020807594)

@meglister @geovgy pls check
